# Generated by Django 3.2.5 on 2022-01-02 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220101_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='team_group',
        ),
    ]
