# Generated by Django 3.2.5 on 2022-01-02 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_team_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_basic_user',
            new_name='is_designer',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[(1, 'Administrator'), (2, 'Project Manager'), (3, 'Developer'), (4, 'Designer')], max_length=1),
        ),
    ]
