# Generated by Django 3.2.5 on 2022-01-02 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(1, 'Administrator'), (2, 'Project Manager'), (3, 'Developer'), (4, 'Designer')], default=1, null=True),
        ),
    ]
