# Generated by Django 3.2.5 on 2022-01-05 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0002_auto_20211019_2253'),
        ('users', '0015_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bugs.project'),
            preserve_default=False,
        ),
    ]
