# Generated by Django 3.2.5 on 2022-01-09 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_team_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='team_group',
        ),
        migrations.AddField(
            model_name='user',
            name='assigned_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_team', to='users.team'),
        ),
        migrations.AddField(
            model_name='user',
            name='managed_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managed_team', to='users.team'),
        ),
    ]
