# Generated by Django 3.2.5 on 2022-01-10 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_remove_team_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='managed_team',
        ),
        migrations.AlterField(
            model_name='team',
            name='manager',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='managed_team', to=settings.AUTH_USER_MODEL),
        ),
    ]
