# Generated by Django 3.2.5 on 2022-01-10 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_user_assigned_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='assigned_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='users.team'),
        ),
    ]
