# Generated by Django 3.2.5 on 2022-04-18 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0008_auto_20220418_1935'),
        ('users', '0026_user_tickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tickets',
            field=models.ManyToManyField(blank=True, related_name='assigned_ticket', to='bugs.Ticket'),
        ),
    ]
