# Generated by Django 3.2.5 on 2022-04-19 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_alter_user_tickets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tickets',
        ),
    ]
