# Generated by Django 3.2.5 on 2022-04-07 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0003_files'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='files',
            options={},
        ),
    ]
