# Generated by Django 3.2.5 on 2022-04-07 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0004_alter_files_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='files',
            options={'verbose_name': 'File', 'verbose_name_plural': 'Files'},
        ),
    ]
