# Generated by Django 3.2.5 on 2021-07-21 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0004_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name_plural': 'tickets'},
        ),
    ]
