# Generated by Django 3.2.5 on 2021-08-11 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0005_alter_ticket_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='attachments',
            new_name='attachment',
        ),
    ]
