# Generated by Django 3.2.5 on 2022-04-13 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0006_auto_20220406_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='attachments',
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('S', 'Submitted'), ('R', 'In Review'), ('A', 'Assigned'), ('C', 'Closed')], default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='files',
            name='img',
            field=models.FileField(upload_to='attachments/%Y/%m/%d'),
        ),
    ]
