# Generated by Django 3.2.5 on 2022-04-18 23:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bugs', '0007_auto_20220412_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='attachments/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
